spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://e-commerce-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}