spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://e-commerce-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: statistics_route
          uri: lb://e-commerce-statistics
          predicates:
            - Path=/api/statistics/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: crawler_route
          uri: lb://e-commerce-crawler
          predicates:
            - Path=/api/craw/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: schedule_route
          uri: lb://e-commerce-schedule
          predicates:
            - Path=/api/schedule/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://e-commerce-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://e-commerce-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: api_order_route
          uri: lb://e-commerce-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://e-commerce-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://e-commerce-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: auth_route
          uri: lb://e-commerce-auth-server
          predicates:
            - Host=auth.gulimall.com

        - id: host_route
          uri: lb://e-commerce-product
          predicates:
            - Host=gulimall.com,item.gulimall.com

        - id: search_route
          uri: lb://e-commerce-search
          predicates:
            - Host=search.gulimall.com

        - id: cart_route
          uri: lb://e-commerce-cart
          predicates:
            - Host=cart.gulimall.com

        - id: order_route
          uri: lb://e-commerce-order
          predicates:
            - Host=order.gulimall.com

        - id: seckill_route
          uri: lb://e-commerce-seckill
          predicates:
            - Host=seckill.gulimall.com

        - id: recommend_route
          uri: lb://e-commerce-recommend
          predicates:
            - Host=recommend.gulimall.com

        - id: admin_route
          uri: lb://e-commerce-backstage
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}